#pragma once
#include <ad/vm/opcodes_def.hpp>
#include <ad/vm/variant.hpp>

#include <map>

namespace ad { namespace vm {
   enum opcodes {
      AD_VM_CONTROL_FLOW_OPS(AD_VM_CREATE_ENUM)
      AD_VM_BR_TABLE_OP(AD_VM_CREATE_ENUM)
      AD_VM_RETURN_OP(AD_VM_CREATE_ENUM)
      AD_VM_CALL_OPS(AD_VM_CREATE_ENUM)
      AD_VM_CALL_IMM_OPS(AD_VM_CREATE_ENUM)
      AD_VM_PARAMETRIC_OPS(AD_VM_CREATE_ENUM)
      AD_VM_VARIABLE_ACCESS_OPS(AD_VM_CREATE_ENUM)
      AD_VM_MEMORY_OPS(AD_VM_CREATE_ENUM)
      AD_VM_I32_CONSTANT_OPS(AD_VM_CREATE_ENUM)
      AD_VM_I64_CONSTANT_OPS(AD_VM_CREATE_ENUM)
      AD_VM_F32_CONSTANT_OPS(AD_VM_CREATE_ENUM)
      AD_VM_F64_CONSTANT_OPS(AD_VM_CREATE_ENUM)
      AD_VM_COMPARISON_OPS(AD_VM_CREATE_ENUM)
      AD_VM_NUMERIC_OPS(AD_VM_CREATE_ENUM)
      AD_VM_CONVERSION_OPS(AD_VM_CREATE_ENUM)
      AD_VM_EXIT_OP(AD_VM_CREATE_ENUM)
      AD_VM_EMPTY_OPS(AD_VM_CREATE_ENUM)
      AD_VM_ERROR_OPS(AD_VM_CREATE_ENUM)
   };
   
   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         AD_VM_CONTROL_FLOW_OPS(AD_VM_CREATE_MAP)
         AD_VM_BR_TABLE_OP(AD_VM_CREATE_MAP)
         AD_VM_RETURN_OP(AD_VM_CREATE_MAP)
         AD_VM_CALL_OPS(AD_VM_CREATE_MAP)
         AD_VM_CALL_IMM_OPS(AD_VM_CREATE_MAP)
         AD_VM_PARAMETRIC_OPS(AD_VM_CREATE_MAP)
         AD_VM_VARIABLE_ACCESS_OPS(AD_VM_CREATE_MAP)
         AD_VM_MEMORY_OPS(AD_VM_CREATE_MAP)
         AD_VM_I32_CONSTANT_OPS(AD_VM_CREATE_MAP)
         AD_VM_I64_CONSTANT_OPS(AD_VM_CREATE_MAP)
         AD_VM_F32_CONSTANT_OPS(AD_VM_CREATE_MAP)
         AD_VM_F64_CONSTANT_OPS(AD_VM_CREATE_MAP)
         AD_VM_COMPARISON_OPS(AD_VM_CREATE_MAP)
         AD_VM_NUMERIC_OPS(AD_VM_CREATE_MAP)
         AD_VM_CONVERSION_OPS(AD_VM_CREATE_MAP)
         AD_VM_EXIT_OP(AD_VM_CREATE_MAP)
         AD_VM_EMPTY_OPS(AD_VM_CREATE_MAP)
         AD_VM_ERROR_OPS(AD_VM_CREATE_MAP)
      };
   }; 

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   AD_VM_CONTROL_FLOW_OPS(AD_VM_CREATE_CONTROL_FLOW_TYPES)
   AD_VM_BR_TABLE_OP(AD_VM_CREATE_BR_TABLE_TYPE)
   AD_VM_RETURN_OP(AD_VM_CREATE_CONTROL_FLOW_TYPES)
   AD_VM_CALL_OPS(AD_VM_CREATE_CALL_TYPES)
   AD_VM_CALL_IMM_OPS(AD_VM_CREATE_CALL_IMM_TYPES)
   AD_VM_PARAMETRIC_OPS(AD_VM_CREATE_TYPES)
   AD_VM_VARIABLE_ACCESS_OPS(AD_VM_CREATE_VARIABLE_ACCESS_TYPES)
   AD_VM_MEMORY_OPS(AD_VM_CREATE_MEMORY_TYPES)
   AD_VM_I32_CONSTANT_OPS(AD_VM_CREATE_I32_CONSTANT_TYPE)
   AD_VM_I64_CONSTANT_OPS(AD_VM_CREATE_I64_CONSTANT_TYPE)
   AD_VM_F32_CONSTANT_OPS(AD_VM_CREATE_F32_CONSTANT_TYPE)
   AD_VM_F64_CONSTANT_OPS(AD_VM_CREATE_F64_CONSTANT_TYPE)
   AD_VM_COMPARISON_OPS(AD_VM_CREATE_TYPES)
   AD_VM_NUMERIC_OPS(AD_VM_CREATE_TYPES)
   AD_VM_CONVERSION_OPS(AD_VM_CREATE_TYPES)
   AD_VM_EXIT_OP(AD_VM_CREATE_EXIT_TYPE)
   AD_VM_EMPTY_OPS(AD_VM_CREATE_TYPES)
   AD_VM_ERROR_OPS(AD_VM_CREATE_TYPES)

   using opcode = variant<
      AD_VM_CONTROL_FLOW_OPS(AD_VM_IDENTITY)
      AD_VM_BR_TABLE_OP(AD_VM_IDENTITY)
      AD_VM_RETURN_OP(AD_VM_IDENTITY)
      AD_VM_CALL_OPS(AD_VM_IDENTITY)
      AD_VM_CALL_IMM_OPS(AD_VM_IDENTITY)
      AD_VM_PARAMETRIC_OPS(AD_VM_IDENTITY)
      AD_VM_VARIABLE_ACCESS_OPS(AD_VM_IDENTITY)
      AD_VM_MEMORY_OPS(AD_VM_IDENTITY)
      AD_VM_I32_CONSTANT_OPS(AD_VM_IDENTITY)
      AD_VM_I64_CONSTANT_OPS(AD_VM_IDENTITY)
      AD_VM_F32_CONSTANT_OPS(AD_VM_IDENTITY)
      AD_VM_F64_CONSTANT_OPS(AD_VM_IDENTITY)
      AD_VM_COMPARISON_OPS(AD_VM_IDENTITY)
      AD_VM_NUMERIC_OPS(AD_VM_IDENTITY)
      AD_VM_CONVERSION_OPS(AD_VM_IDENTITY)
      AD_VM_EXIT_OP(AD_VM_IDENTITY)
      AD_VM_EMPTY_OPS(AD_VM_IDENTITY)
      AD_VM_ERROR_OPS(AD_VM_IDENTITY_END)
      >;
}} // namespace ad::vm
